config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :end_users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :end_users, only: [:index, :show, :edit, :update]
    get 'end_users/:id/order_index' => 'end_users#order_index'
    resources :foods, only: [:new, :index, :show, :edit, :create, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :deliveries, only: [:index, :edit]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    get 'end_users/withdraw_confirm' => 'end_users#withdraw_confirm', as: 'withdraw_confirm'
    patch 'end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    get '/end_users/mypage' => 'end_users#show'
    get 'end_users/infomation/edit' => 'end_users#edit', as: 'edit_end_users'
    patch 'end_users/update' => 'end_users#update'
    patch 'carts/:id' => 'carts#update', as: 'update'
    resources :foods, only: [:index, :show]
    resources :carts, only: [:index]
    get '/orders/completed' => 'orders#completed'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:index, :show, :new, :create]
    resources :deliveries, only: [:index, :edit, :create, :destroy, :update]
    resources :carts, only: [:index, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    delete 'carts/:id' => 'carts#destroy', as: 'destroy'
  end

  devise_scope :admin do
    post 'admins/sign_in', to: 'admin/sessions#sign_in'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord

  has_many :carts, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :food_image

  def get_food_image(width, height)
    food_image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_sales_price
  (tax_free_price * 1.1).round
  end

  def sum_of_price
    food.add_tax_sales_price * order_count
  end

  validates :food_image, presence: true
  validates :genre_id, presence: true
  validates :food_name, presence: true
  validates :introduction, presence: true
  validates :tax_free_price, presence: true
  #validates :sales_status, presence: true これが入るとエラーになる。
end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController

  def new
  @food = Food.new
  end
  
  def index
    @foods = Food.page(params[:page])
  end

  def create
    @food = Food.new(food_params)
      if @food.save
        redirect_to admin_foods_path
      else
        render :new
      end
  end

  def show
    @food_show = Food.find(params[:id])
  end

  def edit
    @food = Food.new
    @food_edit = Food.find(params[:id])
    
    
  end
  def update
    @food =Food.find(params[:id])
    if @food.update(food_params)
      redirect_to admin_foods_path
    else
      render "edit"
    end
  end
  
  private

  def food_params
    params.require(:food).permit(:food_image, :food_name, :introduction, :genre_id, :tax_free_price, :sales_status)
  end
end

app/helpers/admin/foods_helper.rb
module Admin::FoodsHelper
end

app/views/admin/foods/edit.html.erb
<div class="container p-5">
  <div class="row offset-md-2">
    <div class="col-8 mx-auto">
      <h1>商品編集</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-md-4">
  <%= form_with model: @food_edit, url: admin_food_path, method: :patch do |f| %>
        <table>
          <tr>
            <td><%= f.label :"商品画像" %></td>
            <td><%= f.file_field :food_image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td><%= f.label :"商品名" %></td>
            <td><%= f.text_field :food_name %></td>
          </tr>
          <tr>
            <td><%= f.label :"商品説明" %></td>
            <td><%= f.text_field :introduction, style: "width:80%", rows: "5" %></td>
          </tr>
            <td><%= f.label :"ジャンル" %></td>
            <td>
                <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, include_blank: "選択して下さい" %>
            </td>
          <tr>
            <td><%= f.label :"税抜価格" %></td>
            <td><%= f.text_field :tax_free_price %></td>
          </tr>
          <tr>
            <td><%= f.label :"販売ステータス" %></td>
            <td>
            <%= f.radio_button :sales_status, true %>
            <%= f.label :sales_status, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :sales_status, false %>
            <%= f.label :sales_status, "販売停止中", {value: :false, style: "display: inline-block;"} %>
            </td>
          </tr>
          <tr>
          </tr>
      </table>
    <%= f.submit '変更を保存', class:"text-center btn btn-success" %>
  <% end %>
  </div>
</div>

app/views/admin/foods/index.html.erb
<div class="container p-5">
  <div class="row">
    <h1>商品一覧</h1>
    <div class="col-3 offset-9 pb-4">
      <%= link_to "新商品登録", new_admin_food_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="row">
    <table class='table'>
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.id %></td>
            <td><%= link_to admin_food_path(food.id) do %><%= food.food_name %><% end %></td>
            <td>¥<%= food.tax_free_price %></td>
            <td><%= food.genre.genre_name %></td>
            <td><% if food.sales_status %>
            販売中
            <% else %>
            販売停止中
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @foods %>
  </div>
</div>

app/views/admin/foods/new.html.erb
<div class="container p-5">
  <div class="row offset-md-2">
    <div class="col-8 mx-auto">
      <h3>商品新規登録</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-md-4">
      <% if @food.errors.any? %>
      <%= @food.errors.count %>件のエラーが発生しました
      <ul>
        <% @food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
        <%= form_with model: @food, url: admin_foods_path, local: true, method: :post do |f| %>
      <table>
          <tr>
            <td><%= f.label :"商品画像" %></td>
            <td><%= f.file_field :food_image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td><%= f.label :"商品名" %></td>
            <td><%= f.text_field :food_name %></td>
          </tr>
          <tr>
            <td><%= f.label :"商品説明" %></td>
            <td><%= f.text_field :introduction, style: "width:80%", rows: "5" %></td>
          </tr>
          <tr>
            <td><%= f.label :"ジャンル" %></td>
            <td>
                <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, include_blank: "選択して下さい" %>
            </td>
          </tr>
          <tr>
            <td><%= f.label :"税抜価格" %></td>
            <td><%= f.text_field :tax_free_price %></td>
          </tr>
          <tr>
            <td><%= f.label :"販売ステータス" %></td>
            <td>
            <%= f.radio_button :sales_status, true %>
            <%= f.label :sales_status, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :sales_status, false %>
            <%= f.label :sales_status, "販売停止中", {value: :false, style: "display: inline-block;"} %>
            </td>
          </tr>
          <tr>
          </tr>
      </table>
        <div class="button text-center">
        <%= f.submit '新規登録', class:"btn btn-sm btn-success" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/foods/show.html.erb
<div class="container p-5">
  <div class="row offset-md-1">
    <h1>商品詳細</h1>
  </div>
  <div class="row">
    <div class="col-4">
      <%= image_tag @food_show.get_food_image(300, 400)%>
    </div>
    <div class="col-8">
      <table>
        <tr>
          <th>商品名</th>
          <td><%= @food_show.food_name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @food_show.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @food_show.genre.genre_name %></td>
        </tr>
        <tr>
          <th>税込価格（税抜価格）</th>
          <td>¥<%= @food_show.add_tax_sales_price %>(¥<%= @food_show.tax_free_price %>)</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td><% if @food_show.sales_status %>
            販売中
            <% else %>
            販売停止中
            <% end %>
          </td>
        </tr>
      </table>
      <div class="button text-center">
      <%= link_to '商品編集', edit_admin_food_path(@food_show), class:"btn btn-sm btn-success" %>
      </div>
    </div>
  </div>
</div>