config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :end_users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :end_users, only: [:index, :show, :edit, :update]
    get 'end_users/:id/order_index' => 'end_users#order_index'
    resources :foods, only: [:new, :index, :show, :edit, :create, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :deliveries, only: [:index, :edit]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    get 'end_users/withdraw_confirm' => 'end_users#withdraw_confirm', as: 'withdraw_confirm'
    patch 'end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    get '/end_users/mypage' => 'end_users#show'
    get 'end_users/infomation/edit' => 'end_users#edit', as: 'edit_end_users'
    patch 'end_users/update' => 'end_users#update'
    patch 'carts/:id' => 'carts#update', as: 'update'
    resources :foods, only: [:index, :show]
    resources :carts, only: [:index]
    get '/orders/completed' => 'orders#completed'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:index, :show, :new, :create]
    resources :deliveries, only: [:index, :edit, :create, :destroy, :update]
    resources :carts, only: [:index, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    delete 'carts/:id' => 'carts#destroy', as: 'destroy'
  end

  devise_scope :admin do
    post 'admins/sign_in', to: 'admin/sessions#sign_in'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :end_user
  enum order_status: { waiting_pay: 0, check_pay: 1, creating: 2, preparing_send: 3, already_send: 4 }
  enum payment: { credit_card: 0, transfer: 1 }

  def add_tax_sales_price
    (tax_free_price * 1.1).round
  end

  def sum_of_price
    food.add_tax_sales_price * order_count
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!
  def index
    @order = Order.page(params[:page])
  end

  #def index
    #@order = Order.page(params[:page])
  #end

  def show
    @order_show = Order.find(params[:id])
  end
  def update
    @order_show = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
      if @order_show.update(order_params)
         @order_details.update_all(production_status: "production_wait") if @order_show.order_status == "check_pay"
         flash[:notice] = "更新しました"
         redirect_to request.referer
      else
        render "show"
      end
  end

  private

  def order_params
  params.require(:order).permit(:order_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container p-5">
  <div class="row">
    <h1>注文履歴一覧</h1>
    <table class='table'>
      <thead>
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order) do %>
                <%= order.created_at.strftime('%Y/%m/%d') %>
              <% end %>
            </td>
            <td>
              <%= order.end_user.last_name %><%= order.end_user.first_name %>
            </td>
            <td>
              <%= order.order_details.count %>
            </td>
            <td>
              <%= order.order_status_i18n %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @order %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row p-5 ">
    <h1>注文履歴詳細</h1>
  </div>
  <div class="row">
    <div class="col-8">
      <table>
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_orders_path do %>
              <%= @order_show.end_user.last_name %>
              <%= @order_show.end_user.first_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order_show.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order_show.address %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order_show.payment_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order_show, url: admin_order_path(@order_show), method: :patch do |f| %>
              <%= f.select :order_status, Order.order_statuses_i18n.invert,{} %>
              <%= f.submit '更新', class: 'btn btn-success' %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      <table class='table'>
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_show.order_details.each do |order| %>

            <tr>
              <td><%= order.food.food_name %></td>
              <td>¥<%= order.food.add_tax_sales_price %></td>
              <td><%= order.order_detail_count %></td>
              <td><%= order.order_detail_count*order.food.add_tax_sales_price %></td>
              <td>
                <%= form_with model: order, url: admin_order_detail_path(order), method: :patch do |f| %>
                  <%= f.select :production_status, OrderDetail.production_statuses_i18n.invert,{} %>
                  <%= submit_tag '変更', class: 'btn btn-success' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-4 offset-8">
        <table class="table table-bordered">
          <tbody>
            <tr><th>商品合計</th><td><%= @order_show.total_price - 800 %>円</td></tr>
            <tr><th>配送料</th><td>800円</td></tr>
            <tr><th>ご請求額</th><td><%= @order_show.total_price %>円</td></tr>
          </tbody>
        </table>
    </div>
  </div>
</div>