config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :end_users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :end_users, only: [:index, :show, :edit, :update]
    get 'end_users/:id/order_index' => 'end_users#order_index'
    resources :foods, only: [:new, :index, :show, :edit, :create, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :deliveries, only: [:index, :edit]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    get 'end_users/withdraw_confirm' => 'end_users#withdraw_confirm', as: 'withdraw_confirm'
    patch 'end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    get '/end_users/mypage' => 'end_users#show'
    get 'end_users/infomation/edit' => 'end_users#edit', as: 'edit_end_users'
    patch 'end_users/update' => 'end_users#update'
    patch 'carts/:id' => 'carts#update', as: 'update'
    resources :foods, only: [:index, :show]
    resources :carts, only: [:index]
    get '/orders/completed' => 'orders#completed'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:index, :show, :new, :create]
    resources :deliveries, only: [:index, :edit, :create, :destroy, :update]
    resources :carts, only: [:index, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    delete 'carts/:id' => 'carts#destroy', as: 'destroy'
  end

  devise_scope :admin do
    post 'admins/sign_in', to: 'admin/sessions#sign_in'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence:true, length: { minimum: 2, maximum: 20 }
  validates :first_name, presence:true, length: { minimum: 2, maximum: 20 }
  validates :last_name_read, presence:true, length: { minimum: 2, maximum: 20 }
  validates :first_name_read, presence:true, length: { minimum: 2, maximum: 20 }
  validates :post_code, presence:true, length: { minimum: 2, maximum: 20 }
  validates :address, presence:true, length: { minimum: 2, maximum: 20 }
  validates :tel, presence:true, length: { minimum: 2, maximum: 20 }
  validates :email, presence:true, length: { minimum: 2, maximum: 20 }

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    #ページネーション
    #@end_users = EndUser.all
    @end_users = EndUser.page(params[:page])
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
        @end_user =EndUser.find(params[:id])
    if  @end_user.update(end_user_params)
        redirect_to admin_end_user_path
    else
        render "edit"
    end
  end

  def order_index
    @end_user = EndUser.find(params[:id])
    @orders = @end_user.orders.page(params[:page])
  end
  

  private
  # ストロングパラメータ
  def end_user_params
    params.require(:end_user).permit(:last_name, :first_name, :last_name_read, :first_name_read, :post_code, :address, :tel, :email, :is_deleted)
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<%= render 'admin/shared/error_messages', resource: @end_user %>
<div class="container p-5">
  <div class="row offset-md-2">
  <h1><%= @end_user.last_name %><%= @end_user.first_name %>さんの会員情報編集</h1>
  </div>
  <div class="row">
    <div class="col-8 offset-md-4">
  <%= form_with model: @end_user, url: admin_end_user_path, method: :patch do |f| %>
        <table>
           <tr>
            <td><%= f.label :"会員ID" %></td>
            <td><%= @end_user.id %> </td>
          </tr>
          <tr>
            <td><%= f.label :"氏名" %></td>
            <td><%= f.text_field :last_name %> <%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <td><%= f.label :"フリガナ" %></td>
            <td><%= f.text_field :last_name_read %> <%= f.text_field :first_name_read %></td>
          </tr>
          <tr>
            <td><%= f.label :"郵便番号" %></td>
            <td><%= f.text_field :post_code %></td>
          </tr>
          <tr>
            <td><%= f.label :"住所" %></td>
            <td><%= f.text_field :address, style: "width:120%", rows: "5" %></td>
          </tr>
          <tr>
            <td><%= f.label :"電話番号" %></td>
            <td><%= f.telephone_field :tel %></td>
          </tr>
          <tr>
            <td><%= f.label :"メールアドレス" %></td>
            <td><%= f.email_field :email %></td>
          </tr>
          <tr>
            <td><%= f.label :"会員ステータス" %></td>
            <td>
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
            </td>
          </tr>
          <tr>
          </tr>
      </table>
    <%= f.submit '変更を保存', class:"text-center btn btn-success" %>
  <% end %>
  </div>
</div>

app/views/admin/end_users/index.html.erb
<div class="container p-5">
  <div class="row">
    <h1>会員一覧</h1>
    <table class='table'>
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @end_users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= link_to admin_end_user_path(user.id) do %><%= user.last_name %><%= user.first_name %><% end %></td>
            <td><%= user.email %></td>
            <td><% if user.is_deleted %>
            退会
            <% else %>
            有効
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @end_users %>
  </div>
</div>

app/views/admin/end_users/order_index.html.erb
<div class="container p-5">
  <div class="row">
    <h1><%= @end_user.last_name %><%= @end_user.first_name %>さんの注文履歴</h1>
    <table class='table'>
      <thead>
        <tr>
          <th>購入日時</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= link_to admin_order_path(order.id) do %><%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %><% end %></td>
            <td><%= order.order_details.sum(:order_detail_count) %></td>
            <td><%= order.order_status_i18n %></td>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
<%= paginate @orders %>
  </div>
</div>

<!--admin_order(order)-->
<!---->

app/views/admin/end_users/show.html.erb
<div class="container p-5">
  <div class="row offset-md-1">
    <div class="col-8 mx-auto pb-4">
      <h1><%= @end_user.last_name %><%= @end_user.first_name %>様の会員詳細</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-8 mx-auto">
      <table class="table">
        <tr>
          <th>会員ID</th>
          <td><%= @end_user.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @end_user.last_name %><%= @end_user.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @end_user.last_name_read %><%= @end_user.first_name_read %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @end_user.post_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @end_user.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @end_user.tel %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @end_user.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td><% if @end_user.is_deleted %>
            退会
            <% else %>
            有効
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="col-10 d-grid gap-2 d-md-flex justify-content-md-end">
      <div>
        <%= link_to '編集する', edit_admin_end_user_path(@end_user), class:"btn btn-sm btn-success mr-2" %>
      </div>
      <div>
        <%= link_to '注文履歴一覧を見る', admin_path(@end_user), class:"btn btn-sm btn-primary" %>
      </div>
    </div>
  </div>
</div>