config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :end_users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :end_users, only: [:index, :show, :edit, :update]
    get 'end_users/:id/order_index' => 'end_users#order_index'
    resources :foods, only: [:new, :index, :show, :edit, :create, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :deliveries, only: [:index, :edit]
  end

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    get 'end_users/withdraw_confirm' => 'end_users#withdraw_confirm', as: 'withdraw_confirm'
    patch 'end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    get '/end_users/mypage' => 'end_users#show'
    get 'end_users/infomation/edit' => 'end_users#edit', as: 'edit_end_users'
    patch 'end_users/update' => 'end_users#update'
    patch 'carts/:id' => 'carts#update', as: 'update'
    resources :foods, only: [:index, :show]
    resources :carts, only: [:index]
    get '/orders/completed' => 'orders#completed'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:index, :show, :new, :create]
    resources :deliveries, only: [:index, :edit, :create, :destroy, :update]
    resources :carts, only: [:index, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    delete 'carts/:id' => 'carts#destroy', as: 'destroy'
  end

  devise_scope :admin do
    post 'admins/sign_in', to: 'admin/sessions#sign_in'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :end_user
  belongs_to :food

  has_one_attached :food_image

  def get_food_image(width, height)
    food_image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_sales_price
    (tax_free_price * 1.1).round
  end

  def sum_of_price
    food.add_tax_sales_price * order_count
  end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :end_user
  def delivery_address_for_view
  '〒' + post_code + ' ' + address + ' ' + delivery_name
  end

  validates :post_code, presence:true
  validates :address, presence:true
  validates :delivery_name, presence:true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence:true, length: { minimum: 2, maximum: 20 }
  validates :first_name, presence:true, length: { minimum: 2, maximum: 20 }
  validates :last_name_read, presence:true, length: { minimum: 2, maximum: 20 }
  validates :first_name_read, presence:true, length: { minimum: 2, maximum: 20 }
  validates :post_code, presence:true, length: { minimum: 2, maximum: 20 }
  validates :address, presence:true, length: { minimum: 2, maximum: 20 }
  validates :tel, presence:true, length: { minimum: 2, maximum: 20 }
  validates :email, presence:true, length: { minimum: 2, maximum: 20 }

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/food.rb
class Food < ApplicationRecord

  has_many :carts, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :food_image

  def get_food_image(width, height)
    food_image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_sales_price
  (tax_free_price * 1.1).round
  end

  def sum_of_price
    food.add_tax_sales_price * order_count
  end

  validates :food_image, presence: true
  validates :genre_id, presence: true
  validates :food_name, presence: true
  validates :introduction, presence: true
  validates :tax_free_price, presence: true
  #validates :sales_status, presence: true これが入るとエラーになる。
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :foods, dependent: :destroy
  validates :genre_name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :end_user
  enum order_status: { waiting_pay: 0, check_pay: 1, creating: 2, preparing_send: 3, already_send: 4 }
  enum payment: { credit_card: 0, transfer: 1 }

  def add_tax_sales_price
    (tax_free_price * 1.1).round
  end

  def sum_of_price
    food.add_tax_sales_price * order_count
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :food
  belongs_to :order
  
  enum production_status: { production_none: 0, production_wait: 1, production: 2, production_finish: 3 }
  
  def sum_of_price
    food.add_tax_sales_price * order_detail_count
  end
end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController

  def new
  @food = Food.new
  end
  
  def index
    @foods = Food.page(params[:page])
  end

  def create
    @food = Food.new(food_params)
      if @food.save
        redirect_to admin_foods_path
      else
        render :new
      end
  end

  def show
    @food_show = Food.find(params[:id])
  end

  def edit
    @food = Food.new
    @food_edit = Food.find(params[:id])
    
    
  end
  def update
    @food =Food.find(params[:id])
    if @food.update(food_params)
      redirect_to admin_foods_path
    else
      render "edit"
    end
  end
  
  private

  def food_params
    params.require(:food).permit(:food_image, :food_name, :introduction, :genre_id, :tax_free_price, :sales_status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path
  end

 private

  # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_homes_top_path
    else
      root_path
    end
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource_or_scope)

    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/foods_helper.rb
module Admin::FoodsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin-header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-body border-bottom border-dark">
    <div class="container">
      <a class="navbar-brand text-dark m-2" href="/"><h1><%= image_tag 'nagano-cake2.jpeg', size: "200x100"%></h1></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to '商品一覧', admin_foods_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%= link_to '会員一覧', admin_end_users_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%= link_to '注文履歴一覧', admin_homes_top_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%= link_to 'ジャンル一覧', admin_genres_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
        <% else %>
          <li>
            <%= link_to 'About', homes_about_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%=  link_to '商品一覧', foods_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%=  link_to '新規登録', new_end_user_registration_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%= link_to 'ログイン', admin_genres_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_footer.html.erb
<%= stylesheet_link_tag '_footer' %>
<footer>
  <div class='container pt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>© nagano cake EST.1971</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag '_header' %>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-body border-bottom border-dark">
    <div class="container">
      <a class="navbar-brand text-dark m-2" href="/">
        <h1><%= image_tag 'nagano-cake2.jpeg', size: "200x100"%></h1>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if end_user_signed_in? %>
          <li><strong>〜〜ようこそ、<%= current_end_user.last_name %><%= current_end_user.first_name %>さん〜〜</strong><%= render "searches/search" %></li>
          <li>
            <%= link_to 'マイページ', end_users_mypage_path, class:'nav-link text-light btn btn-dark ml-5' %>
          </li>
          <li>
            <%= link_to '商品一覧', foods_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%= link_to 'カート', carts_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%= link_to 'ログアウト', destroy_end_user_session_path, method: :delete, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
        <% else %>
          <li>
            <%= link_to 'About', homes_about_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%=  link_to '商品一覧', foods_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%=  link_to '新規登録', new_end_user_registration_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
          <li>
            <%= link_to 'ログイン', new_end_user_session_path, class:'nav-link text-light btn btn-dark ml-2' %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GTeamGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if request.fullpath.include? "/admin" %>
      <%= render 'layouts/admin-header' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/searches/_search.html.erb
<div class="search_form">
 <%= form_with url: foods_path, local: true, method: :get do |f| %>
  <%= f.text_field :word %>
  <%= f.submit "検索", class:'btn btn-secondary btn-sm' %>
 <% end %>
</div>

app/views/searches/search.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
 <% if @range == "User" %>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% else %>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% end %>
 <% if @range == "User" %>
  <tbody>
   <% @users.each do |user| %>
    <tr>
     <td><%= image_tag user.get_profile_image, size:'100x100' %></td>
     <td><%= user.name %></td>
     <td><%= link_to 'Show', user %></td>
    </tr>
   <% end %>
  </tbody>
 <% else %>
  <tbody>
   <% @books.each do |book| %>
    <tr>
     <td><%= image_tag book.user.get_profile_image, size:'100x100' %></td>
     <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%= book.body %></td>
    </tr>
   <% end %>
  </tbody>
 <% end %>
</table>